///////////////////////////////////////////////////////////
//  Component.cs
//  Implementation of the Class Component
//  Generated by Enterprise Architect
//  Created on:      06-avg-2018 18.29.40
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace ComputerShop.Core
{
    [DataContract]
    [KnownType(typeof(GPU))]
    [KnownType(typeof(RAM))]
    [KnownType(typeof(MotherBoard))]
    [KnownType(typeof(Memory))]
    [KnownType(typeof(Case))]
    [KnownType(typeof(CPU))]
    public abstract class Component : INotifyPropertyChanged {

		private String _model;
		private String _name;
        private Guid _id;
        private Decimal _price;

        public event PropertyChangedEventHandler PropertyChanged;

        [DataMember]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        [DataMember]
        public String Model { get; set; }
        [DataMember]
        public String Name { get; set; }
        [DataMember]
        public Decimal Price { get; set; }
		public Component(){

		}

		~Component(){

		}

	}//end Component

}//end namespace comppkg