///////////////////////////////////////////////////////////
//  GPU.cs
//  Implementation of the Class GPU
//  Generated by Enterprise Architect
//  Created on:      06-avg-2018 18.29.40
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace ComputerShop.Core
{
    [DataContract]
	public class GPU : Component {
        [DataMember]
        public String Memory { get; set; }
        [DataMember]
        public String Speed { get; set; }
        public GPU(){

		}

		~GPU(){

		}

	}//end GPU

}//end namespace comppkg