///////////////////////////////////////////////////////////
//  Memory.cs
//  Implementation of the Class Memory
//  Generated by Enterprise Architect
//  Created on:      06-avg-2018 18.29.40
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace ComputerShop.Core
{
    [DataContract]
	public class Memory : Component {

        [DataMember]
        public String Size { get; set; }
        [DataMember]
        public String MemoryType { get; set; }
        public Memory(){

		}

		~Memory(){

		}

	}//end Memory

}//end namespace comppkg