///////////////////////////////////////////////////////////
//  MotherBoard.cs
//  Implementation of the Class MotherBoard
//  Generated by Enterprise Architect
//  Created on:      06-avg-2018 18.29.40
//  Original author: Teodor Vasiæ
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace ComputerShop.Core
{
    [DataContract]
	public class MotherBoard : Component {
        [DataMember]
        public String Socket { get; set; }
		public MotherBoard(){

		}

		~MotherBoard(){

		}

	}//end MotherBoard

}//end namespace comppkg