///////////////////////////////////////////////////////////
//  RAM.cs
//  Implementation of the Class RAM
//  Generated by Enterprise Architect
//  Created on:      06-avg-2018 18.29.40
//  Original author: Teodor Vasiæ
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace ComputerShop.Core
{
    [DataContract]
	public class RAM : Component {
        [DataMember]
        public String Size { get; set; }
        [DataMember]
        public String RamType { get; set; }
		public RAM(){

		}

		~RAM(){

		}

	}//end RAM

}//end namespace comppkg